In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('D:\Gandhi\Machine Learning\Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
new_df=df.drop(['User ID'],axis='columns')
new_df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [9]:
new_df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [13]:
dummies=pd.get_dummies(df['Gender'])
dummies.head()

Female  Male
0       0     1
1       0     1
2       1     0
3       1     0
4       0     1

In [15]:
concat=pd.concat([new_df,dummies],axis='columns')
concat.head()

Gender  Age  EstimatedSalary  Purchased  Female  Male
0    Male   19            19000          0       0     1
1    Male   35            20000          0       0     1
2  Female   26            43000          0       1     0
3  Female   27            57000          0       1     0
4    Male   19            76000          0       0     1

In [17]:
final=concat.drop(['Gender'],axis='columns')
final.head()

Age  EstimatedSalary  Purchased  Female  Male
0   19            19000          0       0     1
1   35            20000          0       0     1
2   26            43000          0       1     0
3   27            57000          0       1     0
4   19            76000          0       0     1

In [18]:
x=final.drop(['Purchased'],axis='columns')
x.head()

Age  EstimatedSalary  Female  Male
0   19            19000       0     1
1   35            20000       0     1
2   26            43000       1     0
3   27            57000       1     0
4   19            76000       0     1

In [19]:
y=final.Purchased
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [27]:
from sklearn import linear_model
model=linear_model.LogisticRegression()

In [28]:
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [44]:
model.score(x_test,y_test)

0.6375

In [33]:
from sklearn import metrics

In [35]:
coeff=model.coef_
coeff

array([[-9.55796124e-03,  5.72892533e-06, -6.35842561e-02,
        -1.46000277e-01]])

In [38]:
intercept=model.intercept_
intercept

array([-0.20958453])

In [46]:
mae=metrics.mean_absolute_error(y_test,y_pred)
mae

0.3625

In [48]:
mse=np.sqrt(metrics.mean_squared_error(y_test,y_pred))
mse

0.6020797289396148

In [50]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

-0.5466666666666666
